drop table if exists companys;
drop table if exists hibernate_sequence;
drop table if exists orders;
drop table if exists positions;
drop table if exists rols;
drop table if exists sectors;
drop table if exists users;
create table companys (id bigint not null, create_at date, description varchar(255), name varchar(255), update_at date, address varchar(255), web varchar(255), sector bigint, primary key (id)) type=MyISAM;
create table hibernate_sequence (next_val bigint) type=MyISAM;
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
create table orders (id bigint not null, create_at date, update_at date, date_finish date, date_Init date, description varchar(255), title varchar(255), user bigint, primary key (id)) type=MyISAM;
create table positions (id bigint not null, description varchar(255), name varchar(255), primary key (id)) type=MyISAM;
create table rols (id bigint not null, description varchar(255), name varchar(255), primary key (id)) type=MyISAM;
create table sectors (id bigint not null, description varchar(255), name varchar(255), primary key (id)) type=MyISAM;
create table users (id bigint not null, create_at date, update_at date, activated bit, email varchar(255), name varchar(255), password varchar(255), pathPhoto varchar(255), surname varchar(255), company bigint, position bigint, rol bigint, primary key (id)) type=MyISAM;
alter table companys add constraint FKskbw3whm153jkmxjq7hk41fl8 foreign key (sector) references sectors (id);
alter table orders add constraint FKbcyw1rnwiup2kx6tfg4408anm foreign key (user) references users (id);
alter table users add constraint FKpn3pinft49oqkv890bg22yj9n foreign key (company) references companys (id);
alter table users add constraint FKmac8u8mt5osnteoxmr0nfp7k5 foreign key (position) references positions (id);
alter table users add constraint FKf58uvfd5f58s8d6omh5l7dwbf foreign key (rol) references rols (id);
